# Generated by Django 5.2.3 on 2025-06-14 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('subtitle', models.CharField(blank=True, max_length=200, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('upload', models.FileField(blank=True, null=True, upload_to='uploads/')),
                ('category', models.CharField(choices=[('tech', 'Technology'), ('life', 'Lifestyle'), ('news', 'News'), ('other', 'Other')], default='other', max_length=50)),
            ],
        ),
    ]
